name: inkscan_ocr_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  http: ^1.3.0
  google_nav_bar: ^5.0.7
  flutter_localization: ^0.3.2
  intl: ^0.19.0
  country_flags: ^3.2.0
  provider: ^6.1.5
  flutter_localizations:
    sdk: flutter
  share_plus: ^11.0.0
  flutter_tts: ^4.2.2
  rename_app: ^1.6.3
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10
  shared_preferences: ^2.5.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "test/InkScan.png" 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  generate: true
  uses-material-design: true
